server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/order
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 2
    maxActive: 20
    minIdle: 0
    maxWait: 6000
  http:
    multipart:
     max-file-size: 10MB
     max-request-size: 10MB
  #thymeleaf 配置
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    mode: HTML
    encoding: UTF-8
    content-type: text/html
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dh.order.model
  configuration:
    map-underscore-to-camel-case: true
# 打印sql
logging:
  level:
    cn.tycoding.admin.mapper: DEBUG
